### ISSUE TITLE
No failure is thrown when using "--check"

### ISSUE THREAD

**Issue by UnnamedOrange** [puneetmatharu/cmake-format-lint-action#2]
Please check the result of cmake-format and return the corresponding value. Thank you!

**Comment by puneetmatharu** [comment]
Patched. Thanks for pointing this out!

**Comment by UnnamedOrange** [comment]
Sorry to bother you, but I'm not sure whether this bug has been solved. Here is my log:

![image](https://user-images.githubusercontent.com/33177912/156924281-59882da2-3ef4-4d1f-8499-31f5104587e4.png)

It can been seen that there was an error, but the result was a √. I'm sorry that I don't know the grammar of the shell script, thereform I cannot revise it myself. Please help. Thanks!

**Comment by puneetmatharu** [comment]
Ah, my apologies. Can you try it again please? It should work now

**Comment by UnnamedOrange** [comment]
![image](https://user-images.githubusercontent.com/33177912/156928725-f8cf67c5-36a6-4bd1-9ead-aed58cddd2f3.png)

It works! Thanks for your contribution and your awesome action!

**Comment by bwrsandman** [comment]
This issue is still present when using multiple cmake files. A fix is possible with #3
